Iter13
bbquite/mca-server pull request #13
Opened 2024-09-30 13:53 UTC by bbquite

2024-10-04 07:14 UTC, nburunova requested changes

2024-10-04 07:14 UTC, nburunova commented on internal/handlers/agent.go
> +	logger.Debugf("RESP %s %s", url, response.Status)
тут раньше была проверка статуса на 200, теперь не нужна?

2024-10-04 07:14 UTC, nburunova commented on internal/handlers/agent.go
> +		logger.Debugf("RESP %s %s", url, response.Status)
проверка статуса на 200 не нужна?

2024-10-04 07:14 UTC, nburunova commented on internal/service/service.go
> +	var ph = metricResult
зачем тут две переменные, на один и тот же объект?

2024-10-04 07:14 UTC, nburunova commented on internal/service/service.go
> +		return ph, err
вот тут могут быть данные от counter-ов

2024-10-04 07:14 UTC, nburunova commented on internal/service/service.go
> +		return []byte{}, err
тут можно nil вернуть вместо []byte{} ? или вызывающий эту функцию не ожидает такого ответа?

2024-10-04 07:14 UTC, nburunova commented on internal/service/service.go
> +func (s *MetricService) PingDatabase() error {
проверь все методы s *MetricService - должны ли они все быть публичными? или может какие-то стоит не светить наружу и сделать приватными?

2024-10-04 07:14 UTC, nburunova commented on internal/storage/database.go
> +		return &DBStorage{}, err
тут можно nil возвращать, дефолтное значение для указателей, слайсов и мап - это nil

2024-10-04 07:14 UTC, nburunova commented on internal/utils/shasing.go
> +package utils
опечатка в названии файла

2024-10-07 06:40 UTC, bbquite commented on internal/app/agent.go
> +			// err := handlers.MetricsURIRequest(agentServices, cfg.Host, agentLogger)
В агенте это нужно для быстрого переключения режимов работы: по url, по json единично, и батчами

2024-10-07 06:43 UTC, bbquite commented on internal/handlers/agent.go
> +		logger.Debugf("RESP %s %s", url, response.Status)
это просто для личного дебага было, проверка ничего не давала для дальнейшего исполнения. Переделал на короткую запись в 113 строке

2024-10-07 14:49 UTC, bbquite commented on internal/storage/database.go
> +		return &DBStorage{}, err
+

2024-10-07 14:51 UTC, bbquite commented on internal/service/service.go
> +func (s *MetricService) PingDatabase() error {
они все используются снаружи

2024-10-07 14:56 UTC, bbquite commented on internal/handlers/server.go
> +			h.logger.Error(err)
эта часть тоже из 14 инкремента, будет испраленно при сдаче 15

2024-10-07 14:56 UTC, bbquite commented on internal/handlers/server.go
> +		shaHeaderSign, err := hex.DecodeString(r.Header.Get("HashSHA256"))
будет исправлено при сдаче 15 инкремента

2024-10-07 14:57 UTC, bbquite commented on internal/handlers/agent.go
> +	logger.Debugf("RESP %s %s", url, response.Status)
по заданию этого нет, это был личный лог для дебага

2024-10-07 15:00 UTC, bbquite commented on internal/handlers/agent.go
> +func MetricsURIRequest(services *service.MetricService, host string, logger *zap.SugaredLogger) error {
ошибка возвращается когда не удалось получить метрики из инмемори хранилища агента

2024-10-07 15:02 UTC, bbquite commented on internal/handlers/agent.go
> +func MetricsURIRequest(services *service.MetricService, host string, logger *zap.SugaredLogger) error {
done

2024-10-07 15:03 UTC, bbquite commented on internal/service/service.go
> +	var ph = metricResult
done

2024-10-07 15:04 UTC, bbquite commented on internal/service/service.go
> +		return ph, err
done

2024-10-07 15:59 UTC, bbquite commented on internal/app/agent.go
> +}
done

2024-10-07 16:01 UTC, merged