Iter15
bbquite/mca-server pull request #16
Opened 2024-10-12 13:42 UTC by bbquite

2024-10-16 20:37 UTC, nburunova requested changes

2024-10-16 20:37 UTC, nburunova commented on internal/app/agent.go
> +	close(metricsQueue)
тут может быть такая ситуация: ты отмняешь контекст, закрываешь канал, а горутина pushMetricsToQueue НЕ в кейсе ctx.Done, а в metrics, err := services.GetAllMetrics(), собирает метрики. Потом одна добирается до отправки метрик в канал, а канал закрыт уже! Получим панику. 
Есть правило, что тот кто пишет в канал, в твоем случае это горутина pushMetricsToQueue, создает канал и закрывает его. В pushMetricsToQueue ты можешь создавать metricsQueue и возвращать его.

Посмотри пример листинга кода в разделе  Data generation/collecting/loading https://go101.org/article/channel-use-cases.html

2024-10-16 20:37 UTC, nburunova commented on cmd/agent/main.go
> +		err = app.RunAgent()
давай этот if уберем, всегда будет async

2024-10-16 20:37 UTC, nburunova commented on internal/app/agent.go
> +		case metric := <-queue:
тут иногда можем последнее значение не отправить. Допустим ситуация, когда контекст отменен, и в то же время в канале есть данные на отправку. Select выбрал case с ctx.Done(), и последнее значение из канала не отправилось. Я бы горутину отправки завершала, только когда все из queue отправлено

2024-10-16 20:37 UTC, nburunova commented on internal/handlers/server.go
> +	//chiRouter.Use(middleware.RequestsLoggingMiddleware(h.logger))
попал закоменченный код

2024-10-16 20:37 UTC, nburunova commented on internal/handlers/server.go
> +		w.WriteHeader(http.StatusInternalServerError)
не хочешь все таки пользователю API отправить распечатку ошибки? А то только 500 код получит и сиди гадай, что не так было :)

2024-10-16 20:37 UTC, nburunova commented on internal/middleware/sign.go
> +				//log.Printf(`
попал закоментированный код

2024-10-17 15:21 UTC, bbquite commented on internal/middleware/sign.go
> +				//log.Printf(`
done

2024-10-17 15:23 UTC, bbquite commented on internal/handlers/server.go
> +		w.WriteHeader(http.StatusInternalServerError)
но мы ведь записали в лог ошибку. Я почему то думал что все 5... ошибки должны оставаться на стороне сервера, а 4... можно возвращать

2024-10-17 15:24 UTC, bbquite commented on cmd/agent/main.go
> +		err = app.RunAgent()
done

2024-10-18 15:13 UTC, bbquite commented on internal/app/agent.go
> +	close(metricsQueue)
done

2024-10-18 15:13 UTC, bbquite commented on internal/handlers/server.go
> +	//chiRouter.Use(middleware.RequestsLoggingMiddleware(h.logger))
done

2024-10-18 15:25 UTC, bbquite commented on internal/app/agent.go
> +		case metric := <-queue:
done

2024-10-21 16:44 UTC, nburunova commented on internal/app/agent.go
> +		case metric := <-queue:
такое решение тоже можно, но более классическим будет делать
defer wg.Done()
 for metric := range queue { send }
когда канал queue будет закрыт, то range дочитает его доконца, а потом for завершится и сработает wg.Done. 

То есть ты сделаешь cancel() контекста -> в pushMetricsToQueue ты закроешь queue канал на ctx.Done -> и потом дождешься wg.Wait, wg.Wait будет ждать , пока for не отработает доконца канала

2024-10-21 16:44 UTC, nburunova commented on internal/handlers/server.go
> +		w.WriteHeader(http.StatusInternalServerError)
ну так тоже можно, давай так оставим

2024-10-22 19:01 UTC, bbquite commented on internal/app/agent.go
> +		case metric := <-queue:
done

2024-10-23 19:25 UTC, nburunova requested changes

2024-10-23 19:25 UTC, nburunova commented on internal/app/agent.go
> +		case metric := <-queue:
поинт был в том, чтобы не передавать ctx и не использовать select, а сделать range по каналу. Почитай внимательнее мой комментарий

2024-10-25 11:35 UTC, merged