Iter9
bbquite/mca-server pull request #9
Opened 2024-08-15 12:18 UTC by bbquite

2024-08-20 20:23 UTC, avhitrov requested changes
Есть несколько замечаний по реализации, как со старых инкрементов, так и новых. В комментариях к коду.

2024-08-20 20:23 UTC, avhitrov commented on internal/handlers/html/index.gohtml
> +            <i>({{ .type }})</i> / <b>{{ .id }}</b><span>: {{ .value }}</span>
В текущей реализации в данном шаблоне gauge отображаются нормально, а счетчик - пустой.

2024-08-20 20:23 UTC, avhitrov commented on internal/middleware/compress.go
> +func GzipMiddleware(next http.Handler) http.Handler {
Реализована только мидлварь, которая отвечает за сжатие выходных данных. Если отправить данные на вход с gzip-сжатием, возникает ошибка:
```
curl -v --compressed --data-binary @body.json.gz -H "Content-Type: application/json" -H "Content-Encoding: gzip" -X POST http://192.168.160.1:8080/update/
```
В логах:
```
2024-08-20T23:14:12.391+0300    INFO    handlers/server.go:77   invalid character '\x1f' looking for beginning of value
2024-08-20T23:14:12.394+0300    INFO    middleware/logger.go:55 method POST status 400 uri /update/ size 56 duration 3.6317ms
```
Требуется еще одна мидлварь.

2024-08-20 20:23 UTC, avhitrov commented on internal/server/server.go
> +		for {
Не учтена опция из ТЗ, когда значение storeInterval установлено в ноль (`-i=0`). В этом случае запись в файл должна быть синхронизирована с записью в память, а не лупить в потоке бесконечного цикла без таймаутов.

2024-09-09 17:03 UTC, bbquite commented on internal/handlers/agent.go
> +func MetricsJSONRequest(services *service.MetricService, host string, logger *zap.SugaredLogger) error {
+

2024-09-09 17:03 UTC, bbquite commented on internal/handlers/html/index.gohtml
> +            <i>({{ .type }})</i> / <b>{{ .id }}</b><span>: {{ .value }}</span>
+

2024-09-10 14:05 UTC, bbquite commented on internal/middleware/compress.go
> +func GzipMiddleware(next http.Handler) http.Handler {
не воспроизводится, отправил скрины в пачке

2024-09-10 14:40 UTC, bbquite commented on internal/server/server.go
> +		for {
fix

2024-09-15 19:32 UTC, avhitrov commented on internal/middleware/compress.go
> +func GzipMiddleware(next http.Handler) http.Handler {
```
echo '{ "id": "PollCount", "type": "counter", "delta": 10 }` > body.json
gzip body.json
curl -v -s --compressed --data-binary @body.json.gz -H "Content-Type: application/json" -H "Content-encoding: gzip" -X POST http://127.0.0.1:8080/update/
```
В ответ получаем:
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> POST /update/ HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.58.0
> Accept: */*
> Accept-Encoding: deflate, gzip
> Content-Type: application/json
> Content-encoding: gzip
> Content-Length: 78
>
* upload completely sent off: 78 out of 78 bytes
< HTTP/1.1 400 Bad Request
< Content-Encoding: gzip
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Sun, 15 Sep 2024 19:27:26 GMT
< Content-Length: 84
<
invalid character '\x1f' looking for beginning of value
* Connection #0 to host 127.0.0.1 left intact
```
В логах сервера:
```
2024-09-15T22:27:22.741+0300    INFO    middleware/logger.go:55 method POST headers map[Accept:[*/*] Accept-Encoding:[deflate, gzip] Content-Encoding:[gzip] Content-Length:[78] Content-Type:[application/json] User-Agent:[curl/7.58.0]] status 404 uri /update size 47 duration 1.0292ms
2024-09-15T22:27:26.753+0300    DEBUG   handlers/server.go:73   | req )s�c ♥body.json ��R ☻��¶%+♣����∟��Ҽ↕%↔�pIeA*H"↓$�Z♦‼NI�)I♦�←→p�☻ ��↔�A
2024-09-15T22:27:26.755+0300    INFO    handlers/server.go:77   invalid character '\x1f' looking for beginning of value
2024-09-15T22:27:26.756+0300    INFO    middleware/logger.go:55 method POST headers map[Accept:[*/*] Accept-Encoding:[deflate, gzip] Content-Encoding:[gzip] Content-Length:[78] Content-Type:[application/json] User-Agent:[curl/7.58.0]] status 400 uri /update/ size 84 duration 2.5845ms
```

2024-09-15 19:37 UTC, avhitrov requested changes
1. Прошу не резолвить мои замечания, я это делаю сам, когда проверяю выполнение.
2. В результате одно из замечаний было зарезолвлено, но не исправлено.
3. Методика тестирования - в комментариях. Одновременно поднял сервер и из соседнего терминального окна (на самом деле из-под виртуалки с linux) тестировал с помощью curl. Сразу скажу - Postman не умеет слать сжатое содержимое. Можно поставить виндовый curl, а тело сжать с помощью 7-zip.

2024-09-19 18:35 UTC, avhitrov approved these changes
Все ок.

2024-09-20 07:55 UTC, merged